# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0002_projects'),
    ]

    operations = [
        migrations.CreateModel(
            name='servers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30)),
                ('hostname', models.CharField(max_length=30)),
                ('type', models.CharField(max_length=30)),
                ('os', models.CharField(max_length=30)),
            ],
        ),
    ]
