# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0003_servers'),
    ]

    operations = [
        migrations.DeleteModel(
            name='users',
        ),
        migrations.AlterField(
            model_name='servers',
            name='ip',
            field=models.GenericIPAddressField(protocol='IPv4'),
        ),
    ]
