# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 06:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0006_auto_20161028_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=100, null=True),
        ),
    ]
