# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0008_auto_20161028_1453'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventorys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groupid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnsibleWebApp.groups')),
                ('serverid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AnsibleWebApp.servers')),
            ],
        ),
    ]
