# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 07:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0009_inventorys'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorys',
            name='groupid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventorys2groups', to='AnsibleWebApp.groups'),
        ),
        migrations.AlterField(
            model_name='inventorys',
            name='serverid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_inventorys2servers', to='AnsibleWebApp.servers'),
        ),
    ]
