# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0010_auto_20161028_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorys',
            old_name='groupid',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='inventorys',
            old_name='serverid',
            new_name='server',
        ),
    ]
