# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0011_auto_20161028_1628'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorys',
            old_name='group',
            new_name='groups',
        ),
        migrations.RenameField(
            model_name='inventorys',
            old_name='server',
            new_name='servers',
        ),
    ]
