# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-28 08:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AnsibleWebApp', '0012_auto_20161028_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inventorys',
            old_name='groups',
            new_name='grp',
        ),
        migrations.RenameField(
            model_name='inventorys',
            old_name='servers',
            new_name='ser',
        ),
    ]
